ansible_ssh_private_key_file: /root/.ssh/id_ed25519
ansible_python_interpreter: /usr/bin/python3.11
labuser_password: "$6$o59abKRg.47rkZ8R$hFtUleqUslQLYti5jDWP7tbMhwvBHHDPUwpoclsw7A2FQAuirP.UBHqqo5PyMRzcjBysTWIbLin9j3PI7e1Je0"
